name: Build Universal

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false

      - name: Build Common.ExternalConsole
        run: |
          cd "Common.ExternalConsole"
          dotnet build -c Release
          cd ".."
